---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiapp-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: multiapp-server
          image: drdre08/multi-server
          ports:
            - containerPort: 30002
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: multiapp-postgres
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
