apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-pv1
spec:
  storageClassName: managed-nfs-storage # if default then no need to specify
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
