apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-staging
  namespace: default
spec:
  secretName: staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.${userDomain}"
  dnsNames:
  - "local.${userDomain}"
  - "*.local.${userDomain}"
  