apiVersion: cert-manager.io/v1    
kind: Certificate
metadata:
  name: cert-production
  namespace: default
spec:
  secretName: production-tls      
  issuerRef:
    name: letsencrypt-production  
    kind: ClusterIssuer
  commonName: "*.local.${userDomain}"
  dnsNames:
  - "local.${userDomain}"
  - "*.local.${userDomain}"
  