apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  # Generate an API token and NOT a global API key https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens
  cloudflare-token: 4qbld0V7LdzRLptZX-RFfJq4dO8mGqJLjyj3R2FV
