apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${userEmail}
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
#    - http01:
#        ingress:
#          class: traefik-ingress
    - dns01:
        cloudflare:
          email: ${userEmail}
          apiTokenSecretRef:
            name: cloudflare-token-secret
            key: cloudflare-token
      selector:
        dnsZones:
          - "${userDomain}"
